version: '2'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  monolith:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    command: ./run.sh
    depends_on:
      - db
