version: '3.7'

services:
  monolith:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    command: ./run.sh
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
