version: '3.7'

services:
  middleman:
    image: minusz/middleman:latest
    ports:
      - "80:80"
    depends_on:
      - monolith

  monolith:
    image: minusz/monolith:latest
    build:
      context: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: minusz-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5432"

volumes:
  postgres_data:

